name: "scraper-cicd"
on:
  push:
    paths:
      - 'mortgage_scraper/**'
      - 'tests/**'
      - 'conftest.py'
      - '.github/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: run-linting
        run: python3 -m pip install flake8 && python3 -m flake8 tests mortgage_scraper

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -r requirements.txt
      - name: test
        run: >
          pytest -k "not skandia" # skandia has currently closed off access to their endpoint
