name: "scraper-cicd"
on:
  push:
    paths:
      - "mortgage_scraper/**"
      - "tests/**"
      - "conftest.py"
      - ".github/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: run-linting
        run: python3 -m pip install flake8 && python3 -m flake8 tests mortgage_scraper

  # matrix is split across to jobs to avoid wasting free tier cycles
  test-single-platform-backward-comp:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -r requirements.txt
      - name: test
        run: >
          pytest

  test-cross-platform-backward-comp:
    needs: test-single-platform-backward-comp
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -r requirements.txt
      - name: test
        run: >
          pytest
